### PR TITLE
The `asm!` macro was renamed to `llvm_asm!`

### PR DESCRIPTION
**Pull request by phil-opp**
This fixes compilation on latest nightly.

### CODE REVIEW

**Review by emk — APPROVED** [review]
This looks great! Thank you.

Do you need me to make a new crate release? I'd be happy to do so.

**Comment by emk** [comment]
I've released this as `cpuio = "0.3.0"`, because it's incompatible with older stable compilers. Thank you for the PR!

**Comment by emk** [comment]
I've also released `pic8259_simple = "0.2.0"`.

**Comment by phil-opp** [comment]
Thanks a lot for the quick merge and releases!

**Pull request merged**
